# arguments for dataset
dataset: coco
data_root: /yinghepool/Public_data/coco2017
nclass: 81
crop_size: 518

# arguments for training
epochs: 20
batch_size: 20 # per GPU x 4 GPUs
lr: 0.000005
lr_multi: 40.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: dpt
backbone: dinov2_vitb14_base
lock_backbone: False
